name: test
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      os: ubuntu-latest
      go-version: 1.19.x
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: go test 
